class ClassObjServices {
    constructor () {
      this.desarrollo = {
        title: "Desarrollo Web",
        text1: "WordPress",
        img1: '../../public/calidad.png',
        text2: "Estatico",
        img2: '../../public/calidad.png',
        text3: "Dinamico e Iteligente",
        img3: '../../public/calidad.png',
        text4: "Landing Pages",
        img4: '../../public/calidad.png',
        text5: "Muros & Foros",
        img5: '../../public/calidad.png',
        text6: "Micrositios",
        img6: '../../public/calidad.png',
      }
      this.ecommerce = {
        title: "eCommerce",
        text1: "Diseño & Desarrollo de Tiendas",
        img1: '../../public/calidad.png',
        text2: "WordPress, WooCommerce & Shopify",
        img2: '../../public/calidad.png',
        text3: "Sistema de pagos & Multiples Aplicaciones",
        img3: '../../public/calidad.png',
        text4: "Gestion de Inventario & Canales de Ventas",
        img4: '../../public/calidad.png',
        text5: "Desarrollo de Funciones personalizadas",
        img5: '../../public/calidad.png',
        text6: "Mantenimieto, Analisis & Soporte Continuo",
        img6: '../../public/calidad.png',
      }
      this.integrations = {
        title: "Integraciones",
        text1: "Item 1",
        img1: '../../public/calidad.png',
        text2: "Item 2",
        img2: '../../public/calidad.png',
        text3: "Item 3",
        img3: '../../public/calidad.png',
        text4: "Item 4",
        img4: '../../public/calidad.png',
        text5: "Item 5",
        img5: '../../public/calidad.png',
        text6: "Item 6",
        img6: '../../public/calidad.png',
      }
      this.support = {
        title: "Soporte",
        title: "Integraciones",
        text1: "Item 1",
        img1: '../../public/calidad.png',
        text2: "Item 2",
        img2: '../../public/calidad.png',
        text3: "Item 3",
        img3: '../../public/calidad.png',
        text4: "Item 4",
        img4: '../../public/calidad.png',
        text5: "Item 5",
        img5: '../../public/calidad.png',
        text6: "Item 6",
        img6: '../../public/calidad.png',
    }
      this.optimizatios = {
        title: "Optimizaión",
        title: "Integraciones",
        text1: "Item 1",
        img1: '../../public/calidad.png',
        text2: "Item 2",
        img2: '../../public/calidad.png',
        text3: "Item 3",
        img3: '../../public/calidad.png',
        text4: "Item 4",
        img4: '../../public/calidad.png',
        text5: "Item 5",
        img5: '../../public/calidad.png',
        text6: "Item 6",
        img6: '../../public/calidad.png',
    }
      this.appWeb = {
        title: "Aplicaciones Web",
        title: "Integraciones",
        text1: "Item 1",
        img1: '../../public/calidad.png',
        text2: "Item 2",
        img2: '../../public/calidad.png',
        text3: "Item 3",
        img3: '../../public/calidad.png',
        text4: "Item 4",
        img4: '../../public/calidad.png',
        text5: "Item 5",
        img5: '../../public/calidad.png',
        text6: "Item 6",
        img6: '../../public/calidad.png',
    }
    }
  }
  export const ObjServices = new ClassObjServices() ;