class ClassObjServices {
    constructor () {
      this.desarrollo = {
        title: "Desarrollo Web",
        text1: "Ecosistema JavaScript, TypeScript & React.js",
        img1: './icons/js.svg',
        text2: "WordPress",
        img2: './icons/wordpress.svg',
        text3: "Contenido Dinamico & Web Iteligente",
        img3: './icons/idea_icon.svg',
        text4: "Landing Pages & Sale Pages",
        img4: './icons/landing_icon.svg',
        text5: "Aplicaciones Web & Algoritmos",
        img5: './icons/murosforos_icon.svg',
        text6: "Micrositios, One Page & QR",
        img6: './icons/smallsite_icon.svg',
      }
      this.ecommerce = {
        title: "eCommerce",
        text1: "Diseño & Desarrollo de Tiendas",
        img1:'./icons/store_icon.svg',
        text2: "WordPress, WooCommerce & Shopify",
        img2: './icons/wordpress.svg',
        text3: "Sistema de pagos & Multiples Aplicaciones",
        img3: './icons/pay_icon.svg',
        text4: "Gestion de Inventario & Canales de Ventas",
        img4: './icons/sale_icon.svg',
        text5: "Desarrollo de Funciones personalizadas",
        img5: './icons/newfunction_icon.svg',
        text6: "Mantenimieto, Analisis & Soporte Continuo",
        img6: './icons/support_icon.svg',
      }
      this.integrations = {
        title: "Integraciones",
        text1: "CRM",
        img1: './icons/crm_icon.svg',
        text2: "Sistema De Pagos",
        img2: './icons/pay_icon.svg',
        text3: "Redes Sociales",
        img3: './icons/socialmedia_icon.svg',
        text4: "Analisis & Metricas",
        img4: './icons/metric_icon.svg',
        text5: "Email & Subcripcion",
        img5: './icons/mail_icon.svg',
        text6: "Envio e Inventario",
        img6: './icons/transport_icon.svg',
      }
      this.supportOptimizatios = {
        title: "Soporte",
        text1: "Auditoria",
        img1: './icons/audit_icon.svg',
        text2: "Nuevas Funcionalidades",
        img2: './icons/newfunction_icon.svg',
        text3: "Solucion de errores",
        img3: './icons/warning_icon.svg',
        text4: "SEO & Metricas",
        img4: './icons/metric_icon.svg',
        text5: "Soporte de Codigo",
        img5: './icons/support_icon.svg',
        text6: "Actualizaciones",
        img6: './icons/newfunction_icon.svg',
      }
      this.appWeb = {
        title: "Aplicaciones Web",
        text1: "Proyectos de Software",
        img1: './icons/projectIcon.svg',
        text2: "Web Inteligentes",
        img2: './icons/idea_icon.svg',
        text3: "Web & eCommerce Nativo",
        img3: './icons/code_icon.svg',
        text4: "Apicaciones Web",
        img4: './icons/mobile_icon.svg',
        text5: "Algoritmos",
        img5: './icons/algorithm_icon.svg',
        text6: "otros",
        img6: './icons/other_icon.svg',
    }
    }
  }
  export const ObjServices = new ClassObjServices() ;